namespace WarBox.Content;

internal static class WarBoxActors
{
    private static readonly UnityEngine.Color white = new UnityEngine.Color(1f, 1f, 1f);

    public static void Init()
    {
        AddVehicles();
    }

    private static void AddVehicles()
    {
        var base_warunit = AssetManager.actor_library.clone("base_warunit", "$basic_unit$");
        base_warunit.is_humanoid = false;
        base_warunit.civ = false;
        base_warunit.experience_given = 20;
        base_warunit.actor_size = ActorSize.S13_Human;
        base_warunit.die_in_lava = false;
        base_warunit.can_have_subspecies = false;
        base_warunit.base_stats["mass_2"] = 600f;
        base_warunit.base_stats["stamina"] = 500f;
        base_warunit.base_stats["lifespan"] = 500f;
        base_warunit.base_stats["scale"] = 0.2f;
        base_warunit.base_stats["size"] = 1f;
        base_warunit.base_stats["mass"] = 1000f;
        base_warunit.base_stats["health"] = 300f;
        base_warunit.base_stats["speed"] = 10f;
        base_warunit.base_stats["armor"] = 20f;
        base_warunit.base_stats["attack_speed"] = 1f;
        base_warunit.base_stats["damage"] = 30f;
        base_warunit.base_stats["knockback"] = 2f;
        base_warunit.base_stats["accuracy"] = 1f;
        base_warunit.base_stats["targets"] = 1f;
        base_warunit.base_stats["area_of_effect"] = 0.5f;
        base_warunit.base_stats["range"] = 1f;
        base_warunit.base_stats["critical_damage_multiplier"] = 2f;
        base_warunit.base_stats["multiplier_supply_timer"] = 1f;
        base_warunit.sound_hit = "event:/SFX/HIT/HitWood";
        base_warunit.base_throwing_range = 1f;
        base_warunit.affected_by_dust = false;
        base_warunit.inspect_children = false;
        base_warunit.default_attack = "base_attack";
        //base_warunit.icon = "iconBoat";
        base_warunit.shadow_texture = "unitShadow_6";
        base_warunit.texture_asset = new ActorTextureSubAsset("actors/tank/", false);
        base_warunit.special = true;
        base_warunit.has_advanced_textures = false;
        base_warunit.cost = new ConstructionCost(1, 0, 0, 1);
        base_warunit.animation_walk = ActorAnimationSequences.walk_0_3;
        base_warunit.animation_idle = ActorAnimationSequences.walk_0;
        base_warunit.animation_swim = ActorAnimationSequences.swim_0_3;
        base_warunit.name_template_sets = AssetLibrary<ActorAsset>.a<string>("assimilator_set");
        base_warunit.kingdom_id_civilization = string.Empty;
        base_warunit.build_order_template_id = string.Empty;
        base_warunit.disable_jump_animation = true;
        base_warunit.inspect_sex = false;
        base_warunit.inspect_show_species = false;
        base_warunit.inspect_generation = false;
        base_warunit.immune_to_injuries = true;
        base_warunit.show_on_meta_layer = true;
        base_warunit.show_in_knowledge_window = false;
        base_warunit.show_in_taxonomy_tooltip = false;
        base_warunit.needs_to_be_explored = false;
        base_warunit.need_colored_sprite = true;
        base_warunit.allowed_status_tiers = StatusTier.Basic;
        base_warunit.render_status_effects = false;
        base_warunit.inspect_avatar_scale = 1.5f;
        base_warunit.force_land_creature = true;
        base_warunit.inspect_home = true;
        base_warunit.can_edit_traits = true;
        base_warunit.can_receive_traits = true;
        base_warunit.flying = false;
        //baseoffensiveunit.tech = "baseoffensiveunits";
        base_warunit.very_high_flyer = false;
        base_warunit.die_on_blocks = true;
        base_warunit.ignore_blocks = false;
        base_warunit.inspect_experience = true;
        base_warunit.inspect_kills = true;
        base_warunit.use_items = false;
        base_warunit.has_baby_form = false;
        base_warunit.take_items = false;
        base_warunit.job_citizen = Toolbox.a<string>("attacker");
        base_warunit.job_kingdom = Toolbox.a<string>("attacker");
        base_warunit.job_attacker = Toolbox.a<string>("attacker");
        base_warunit.job = AssetLibrary<ActorAsset>.a<string>("decision");
        base_warunit.addDecision("check_swearing");
        base_warunit.addDecision("warrior_try_join_army_group");
        base_warunit.addDecision("city_walking_to_danger_zone");
        base_warunit.addDecision("warrior_army_captain_idle_walking_city");
        base_warunit.addDecision("warrior_army_captain_waiting");
        base_warunit.addDecision("warrior_army_leader_move_random");
        base_warunit.addDecision("warrior_army_leader_move_to_attack_target");
        base_warunit.addDecision("warrior_army_follow_leader");
        base_warunit.addDecision("warrior_random_move");
        base_warunit.addDecision("check_warrior_transport");
        base_warunit.addDecision("swim_to_island");
        base_warunit.collective_term = "group_gang";
        base_warunit.prevent_unconscious_rotation = true;
        base_warunit.use_phenotypes = false;
        base_warunit.unit_other = true;
        base_warunit.can_be_surprised = false;
        base_warunit.has_skin = false;
        base_warunit.can_turn_into_mush = false;
        base_warunit.can_turn_into_tumor = false;
        base_warunit.can_turn_into_zombie = false;
        base_warunit.use_tool_items = false;
        base_warunit.kingdom_id_wild = "neutral_animals";
        base_warunit.can_flip = true;
        base_warunit.check_flip = (BaseSimObject _, WorldTile _) => true;
        base_warunit.allow_possession = true;
        base_warunit.can_talk_with = false;
        base_warunit.control_can_backstep = true;
        base_warunit.control_can_jump = true;
        base_warunit.control_can_kick = true;
        base_warunit.control_can_dash = true;
        base_warunit.control_can_talk = false;
        base_warunit.control_can_swear = true;
        base_warunit.control_can_steal = true;
        base_warunit.show_controllable_tip = true;
        base_warunit.update_z = true;
        base_warunit.can_be_killed_by_stuff = true;
        base_warunit.can_be_killed_by_life_eraser = true;
        base_warunit.can_attack_buildings = true;
        base_warunit.can_be_moved_by_powers = true;
        base_warunit.can_be_hurt_by_powers = true;
        base_warunit.effect_damage = false;
        base_warunit.immune_to_slowness = true;
        base_warunit.can_be_inspected = true;
        base_warunit.visible_on_minimap = false;
        base_warunit.color = white;
        base_warunit.death_animation_angle = false;
        base_warunit.shadow = false;
        base_warunit.addTrait("warbox_unit");
        base_warunit.addTrait("fire_blood");
        base_warunit.addTrait("immune");

        ActorAsset tank = AssetManager.actor_library.clone("warbox_tank", "base_warunit");
        tank.texture_asset = new ActorTextureSubAsset("actors/tank/", false);
        tank.shadow_texture = "unitShadow_6";
        tank.sound_hit = "event:/SFX/HIT/HitMetal";
        tank.animation_walk = ActorAnimationSequences.walk_0_3;
        tank.animation_idle = Toolbox.a("idle_0");
        tank.animation_swim = ActorAnimationSequences.swim_0_3;
        tank.default_attack = "tank_attack";
        tank.base_stats["mass_2"] = 5000f;
        tank.base_stats["stamina"] = 500f;
        tank.base_stats["scale"] = 0.2f;
        tank.base_stats["size"] = 3f;
        tank.base_stats["mass"] = 1000f;
        tank.base_stats["health"] = 2500f;
        tank.base_stats["speed"] = 17f;
        tank.base_stats["armor"] = 30f;
        tank.base_stats["attack_speed"] = 0f;
        tank.base_stats["damage"] = 600f;
        tank.base_stats["knockback"] = 2f;
        tank.base_stats["accuracy"] = 1f;
        tank.base_stats["targets"] = 1f;
        tank.base_stats["area_of_effect"] = 2f;
        tank.base_stats["range"] = 24f;
        tank.cost = new ConstructionCost(0, 0, 5, 0);
        tank.color = white;
        tank.name_locale = "spawn_tank";
        tank.power_id = "spawn_tank";
        tank.name_template_sets = AssetLibrary<ActorAsset>.a<string>("tank_set");
        tank.addTrait("block");
        tank.addTrait("deflect_projectile");

        ActorAsset recon_car = AssetManager.actor_library.clone("warbox_recon_car", "warbox_tank");
        recon_car.texture_asset = new ActorTextureSubAsset("actors/recon_car/", false);
        recon_car.base_stats["mass"] = 500f;
        recon_car.base_stats["mass_2"] = 2000f;
        recon_car.base_stats["health"] = 700f;
        recon_car.base_stats["damage"] = 100f;
        recon_car.base_stats["area_of_effect"] = 1f;
        recon_car.base_stats["knockback"] = 0f;
        recon_car.base_stats["attack_speed"] = 5f;
        recon_car.base_stats["accuracy"] = 0.65f;
        recon_car.base_stats["armor"] = 12.5f;
        recon_car.base_stats["speed"] = 30f;
        recon_car.base_stats["range"] = 12f;
        recon_car.default_attack = "auto_cannon";
        recon_car.name_locale = "spawn_recon_car";
        recon_car.power_id = "spawn_recon_car";
        recon_car.animation_swim_speed = 0.5f;
        recon_car.color = white;
        recon_car.addTrait("dodge");
        recon_car.addTrait("dash");
        recon_car.removeTrait("block");
        recon_car.removeTrait("deflect_projectile");
    }
}