using System.Collections.Generic;

namespace WarBox.Content;

internal static class WarBoxActors
{
    private static readonly UnityEngine.Color white = new UnityEngine.Color(1f, 1f, 1f);
    private static readonly string[] idle_0_9 = Toolbox.a("idle_0", "idle_1", "idle_2", "idle_3", "idle_4", "idle_5", "idle_6", "idle_7", "idle_8", "idle_9");

    public static void Init()
    {
        AddVehicles();
    }

    private static void AddVehicles()
    {
        ActorAsset base_warunit = AssetManager.actor_library.clone("base_warunit", "$basic_unit$");
        base_warunit.is_humanoid = false;
        base_warunit.civ = false;
        base_warunit.experience_given = 20;
        base_warunit.actor_size = ActorSize.S13_Human;
        base_warunit.die_in_lava = false;
        base_warunit.can_have_subspecies = false;
        base_warunit.base_stats["mass_2"] = 600f;
        base_warunit.base_stats["stamina"] = 500f;
        base_warunit.base_stats["lifespan"] = 500f;
        base_warunit.base_stats["scale"] = 0.2f;
        base_warunit.base_stats["size"] = 0.5f;
        base_warunit.base_stats["mass"] = 1000f;
        base_warunit.base_stats["health"] = 300f;
        base_warunit.base_stats["speed"] = 10f;
        base_warunit.base_stats["armor"] = 20f;
        base_warunit.base_stats["attack_speed"] = 1f;
        base_warunit.base_stats["damage"] = 30f;
        base_warunit.base_stats["knockback"] = 2f;
        base_warunit.base_stats["accuracy"] = 1f;
        base_warunit.base_stats["targets"] = 1f;
        base_warunit.base_stats["area_of_effect"] = 0.5f;
        base_warunit.base_stats["range"] = 1f;
        base_warunit.base_stats["critical_damage_multiplier"] = 2f;
        base_warunit.base_stats["multiplier_supply_timer"] = 1f;
        base_warunit.sound_hit = "event:/SFX/HIT/HitWood";
        base_warunit.base_throwing_range = 1f;
        base_warunit.affected_by_dust = false;
        base_warunit.inspect_children = false;
        base_warunit.default_attack = "base_attack";
        base_warunit.shadow_texture = "unitShadow_6";
        base_warunit.texture_asset = new ActorTextureSubAsset("actors/tank/", false);
        base_warunit.special = true;
        base_warunit.has_advanced_textures = false;
        base_warunit.cost = new ConstructionCost(1, 0, 0, 1);
        base_warunit.animation_walk = ActorAnimationSequences.walk_0_3;
        base_warunit.animation_idle = ActorAnimationSequences.walk_0;
        base_warunit.animation_swim = ActorAnimationSequences.swim_0_3;
        base_warunit.kingdom_id_civilization = string.Empty;
        base_warunit.build_order_template_id = string.Empty;
        base_warunit.disable_jump_animation = true;
        base_warunit.inspect_sex = false;
        base_warunit.inspect_show_species = false;
        base_warunit.inspect_generation = false;
        base_warunit.immune_to_injuries = true;
        base_warunit.show_on_meta_layer = true;
        base_warunit.show_in_knowledge_window = false;
        base_warunit.show_in_taxonomy_tooltip = false;
        base_warunit.needs_to_be_explored = false;
        base_warunit.need_colored_sprite = true;
        base_warunit.allowed_status_tiers = StatusTier.Basic;
        base_warunit.render_status_effects = false;
        base_warunit.inspect_avatar_scale = 1.5f;
        base_warunit.force_land_creature = true;
        base_warunit.inspect_home = true;
        base_warunit.can_edit_traits = true;
        base_warunit.can_receive_traits = true;
        base_warunit.flying = false;
        base_warunit.very_high_flyer = false;
        base_warunit.die_on_blocks = true;
        base_warunit.ignore_blocks = false;
        base_warunit.inspect_experience = true;
        base_warunit.inspect_kills = true;
        base_warunit.use_items = false;
        base_warunit.has_baby_form = false;
        base_warunit.take_items = false;
        base_warunit.job_citizen = Toolbox.a<string>("attacker");
        base_warunit.job_kingdom = Toolbox.a<string>("attacker");
        base_warunit.job_attacker = Toolbox.a<string>("attacker");
        base_warunit.job = AssetLibrary<ActorAsset>.a<string>("decision");
        base_warunit.addDecision("check_swearing");
        base_warunit.addDecision("warrior_try_join_army_group");
        base_warunit.addDecision("city_walking_to_danger_zone");
        base_warunit.addDecision("warrior_army_captain_idle_walking_city");
        base_warunit.addDecision("warrior_army_captain_waiting");
        base_warunit.addDecision("warrior_army_leader_move_random");
        base_warunit.addDecision("warrior_army_leader_move_to_attack_target");
        base_warunit.addDecision("warrior_army_follow_leader");
        base_warunit.addDecision("warrior_random_move");
        base_warunit.addDecision("check_warrior_transport");
        base_warunit.addDecision("swim_to_island");
        base_warunit.collective_term = "group_gang";
        base_warunit.prevent_unconscious_rotation = true;
        base_warunit.use_phenotypes = false;
        base_warunit.unit_other = true;
        base_warunit.can_be_surprised = false;
        base_warunit.has_skin = false;
        base_warunit.can_turn_into_mush = false;
        base_warunit.can_turn_into_tumor = false;
        base_warunit.can_turn_into_zombie = false;
        base_warunit.use_tool_items = false;
        base_warunit.kingdom_id_wild = "neutral_animals";
        base_warunit.can_flip = true;
        base_warunit.check_flip = (BaseSimObject _, WorldTile _) => true;
        base_warunit.allow_possession = true;
        base_warunit.can_talk_with = false;
        base_warunit.control_can_backstep = true;
        base_warunit.control_can_jump = true;
        base_warunit.control_can_kick = true;
        base_warunit.control_can_dash = true;
        base_warunit.control_can_talk = false;
        base_warunit.control_can_swear = true;
        base_warunit.control_can_steal = true;
        base_warunit.show_controllable_tip = true;
        base_warunit.update_z = true;
        base_warunit.can_be_killed_by_stuff = true;
        base_warunit.can_be_killed_by_life_eraser = true;
        base_warunit.can_attack_buildings = true;
        base_warunit.can_be_moved_by_powers = true;
        base_warunit.can_be_hurt_by_powers = true;
        base_warunit.effect_damage = false;
        base_warunit.immune_to_slowness = true;
        base_warunit.can_be_inspected = true;
        base_warunit.visible_on_minimap = false;
        base_warunit.color = white;
        base_warunit.death_animation_angle = false;
        base_warunit.addTrait("warbox_unit");
        base_warunit.addTrait("fire_blood");
        base_warunit.addTrait("immune");
        base_warunit.texture_asset.loadShadow();

        ActorAsset tank = AssetManager.actor_library.clone("warbox_tank", "base_warunit");
        tank.texture_asset = new ActorTextureSubAsset("actors/tank/", false);
        tank.shadow_texture = "unitShadow_6";
        tank.icon = "actors/tank";
        tank.sound_hit = "event:/SFX/HIT/HitMetal";
        tank.animation_walk = ActorAnimationSequences.walk_0_3;
        tank.animation_idle = Toolbox.a("idle_0");
        tank.animation_swim = ActorAnimationSequences.swim_0_1;
        tank.animation_swim_speed = 0.5f;
        tank.default_attack = "tank_cannon";
        tank.base_stats["mass_2"] = 5000f;
        tank.base_stats["stamina"] = 500f;
        tank.base_stats["scale"] = 0.2f;
        tank.base_stats["size"] = 3f;
        tank.base_stats["mass"] = 1000f;
        tank.base_stats["health"] = 2750f;
        tank.base_stats["speed"] = 17f;
        tank.base_stats["armor"] = 30f;
        tank.base_stats["attack_speed"] = 0f;
        tank.base_stats["damage"] = 600f;
        tank.base_stats["knockback"] = 2f;
        tank.base_stats["accuracy"] = 1f;
        tank.base_stats["targets"] = 1f;
        tank.base_stats["area_of_effect"] = 2f;
        tank.base_stats["range"] = 28f;
        tank.cost = new ConstructionCost(0, 0, 3, 0);
        tank.color = white;
        tank.name_locale = "spawn_tank";
        tank.power_id = "spawn_tank";
        tank.name_template_sets = AssetLibrary<ActorAsset>.a<string>("tank_name");
        tank.addTrait("block");
        tank.addTrait("deflect_projectile");
        tank.texture_asset.loadShadow();

        ActorAsset apc = AssetManager.actor_library.clone("warbox_apc", "warbox_tank");
        apc.texture_asset = new ActorTextureSubAsset("actors/apc/", false);
        apc.icon = "actors/apc";
        apc.base_stats["mass"] = 500f;
        apc.base_stats["mass_2"] = 2000f;
        apc.base_stats["health"] = 1100f;
        apc.base_stats["damage"] = 50f;
        apc.base_stats["area_of_effect"] = 1f;
        apc.base_stats["knockback"] = 0.1f;
        apc.base_stats["attack_speed"] = 11f;
        apc.base_stats["accuracy"] = 0.65f;
        apc.base_stats["armor"] = 10f;
        apc.base_stats["speed"] = 30f;
        apc.base_stats["range"] = 16f;
        apc.default_attack = "machine_gun";
        apc.name_locale = "spawn_apc";
        apc.power_id = "spawn_apc";
        apc.color = white;
        apc.name_template_sets = AssetLibrary<ActorAsset>.a<string>("apc_name");
        apc.addTrait("dodge");
        apc.addTrait("dash");
        apc.removeTrait("block");
        apc.removeTrait("deflect_projectile");
        apc.texture_asset.loadShadow();

        ActorAsset ifv = AssetManager.actor_library.clone("warbox_ifv", "warbox_tank");
        ifv.texture_asset = new ActorTextureSubAsset("actors/ifv/", false);
        ifv.icon = "actors/ifv";
        ifv.base_stats["mass"] = 750f;
        ifv.base_stats["mass_2"] = 3500f;
        ifv.base_stats["health"] = 2000f;
        ifv.base_stats["damage"] = 100f;
        ifv.base_stats["area_of_effect"] = 1f;
        ifv.base_stats["knockback"] = 0f;
        ifv.base_stats["attack_speed"] = 4f;
        ifv.base_stats["accuracy"] = 0.9f;
        ifv.base_stats["armor"] = 20f;
        ifv.base_stats["speed"] = 22f;
        ifv.base_stats["range"] = 20f;
        ifv.default_attack = "auto_cannon";
        ifv.name_locale = "spawn_ifv";
        ifv.power_id = "spawn_ifv";
        ifv.color = white;
        ifv.name_template_sets = AssetLibrary<ActorAsset>.a<string>("ifv_name");
        ifv.addTrait("dodge");
        ifv.addTrait("atgm_launcher");
        ifv.texture_asset.loadShadow();

        ActorAsset spg = AssetManager.actor_library.clone("warbox_spg", "warbox_tank");
        spg.texture_asset = new ActorTextureSubAsset("actors/spg/", false);
        spg.icon = "actors/spg";
        spg.base_stats["mass_2"] = 3000f;
        spg.base_stats["stamina"] = 500f;
        spg.base_stats["scale"] = 0.2f;
        spg.base_stats["size"] = 1f;
        spg.base_stats["mass"] = 1000f;
        spg.base_stats["health"] = 700f;
        spg.base_stats["speed"] = 15f;
        spg.base_stats["armor"] = 10f;
        spg.base_stats["attack_speed"] = 0f;
        spg.base_stats["damage"] = 700f;
        spg.base_stats["knockback"] = 4f;
        spg.base_stats["accuracy"] = 0.1f;
        spg.base_stats["targets"] = 2f;
        spg.base_stats["area_of_effect"] = 2f;
        spg.base_stats["range"] = 1000f;
        spg.base_stats["stamina"] = 1000f;
        spg.inspect_avatar_scale = 2f;
        spg.default_attack = "artillery_cannon";
        spg.name_locale = "spawn_spg";
        spg.power_id = "spawn_spg";
        spg.color = white;
        spg.name_template_sets = AssetLibrary<ActorAsset>.a<string>("spg_name");
        spg.job = AssetLibrary<ActorAsset>.a<string>("decision");
        spg.addDecision("check_swearing");
        spg.addDecision("warrior_try_join_army_group");
        spg.addDecision("artillery_strike");
        //spg.addDecision("city_idle_walking");
        spg.addDecision("warrior_random_move");
        spg.addDecision("swim_to_island");
        spg.removeTrait("block");
        spg.removeTrait("deflect_projectile");
        spg.texture_asset.loadShadow();

        ActorAsset helicopter = AssetManager.actor_library.clone("warbox_helicopter", "base_warunit");
        helicopter.texture_asset = new ActorTextureSubAsset("actors/helicopter/", false);
        helicopter.icon = "actors/helicopter";
        helicopter.die_in_lava = false;
        helicopter.animation_speed_based_on_walk_speed = false;
        helicopter.animation_walk_speed = 10f;
        helicopter.animation_idle_speed = 10f;
        helicopter.animation_swim_speed = 10f;
        helicopter.base_stats["mass_2"] = 2000f;
        helicopter.base_stats["stamina"] = 1000f;
        helicopter.base_stats["scale"] = 0.2f;
        helicopter.base_stats["size"] = 1f;
        helicopter.base_stats["mass"] = 1000f;
        helicopter.base_stats["health"] = 875f;
        helicopter.base_stats["speed"] = 60f;
        helicopter.base_stats["armor"] = 10f;
        helicopter.base_stats["attack_speed"] = 0.3f;
        helicopter.base_stats["damage"] = 1000f;
        helicopter.base_stats["knockback"] = 2f;
        helicopter.base_stats["accuracy"] = 0.7f;
        helicopter.base_stats["targets"] = 1f;
        helicopter.base_stats["area_of_effect"] = 0.5f;
        helicopter.base_stats["range"] = 15f;
        helicopter.inspect_avatar_scale = 0.5f;
        helicopter.default_height = 8f;
        helicopter.sound_hit = "event:/SFX/HIT/HitMetal";
        helicopter.default_attack = "rocket_pod";
        helicopter.special = true;
        helicopter.can_flip = true;
        helicopter.has_advanced_textures = false;
        helicopter.color = white;
        helicopter.animation_walk = ActorAnimationSequences.walk_0_3;
        helicopter.animation_idle = ActorAnimationSequences.walk_0_3;
        helicopter.animation_swim = ActorAnimationSequences.walk_0_3;
        helicopter.actor_size = ActorSize.S17_Dragon;
        helicopter.name_locale = "spawn_helicopter";
        helicopter.power_id = "spawn_helicopter";
        helicopter.flying = true;
        helicopter.very_high_flyer = true;
        helicopter.die_on_blocks = false;
        helicopter.ignore_blocks = true;
        helicopter.shadow_texture = "unitShadow_8";
        helicopter.color = white;
        helicopter.cost = new ConstructionCost(0, 0, 3, 0);
        helicopter.name_template_sets = AssetLibrary<ActorAsset>.a<string>("heli_name");
        helicopter.addDecision("burn_tumors");
        helicopter.addTrait("fire_proof");
        helicopter.addTrait("freeze_proof");
        helicopter.texture_asset.loadShadow();

        ActorAsset bomber = AssetManager.actor_library.clone("warbox_bomber", "warbox_helicopter");
        bomber.icon = "actors/fighter";
        bomber.texture_asset = new ActorTextureSubAsset("actors/fighter/", false);
        bomber.name_locale = "spawn_bomber";
        bomber.power_id = "spawn_bomber";
        bomber.base_stats["mass_2"] = 2000f;
        bomber.base_stats["stamina"] = 1000f;
        bomber.base_stats["scale"] = 0.2f;
        bomber.base_stats["size"] = 1f;
        bomber.base_stats["mass"] = 1000f;
        bomber.base_stats["health"] = 1500f;
        bomber.base_stats["speed"] = 60f;
        bomber.base_stats["armor"] = 10f;
        bomber.base_stats["attack_speed"] = -10f;
        bomber.default_height = 12f;
        bomber.animation_walk = ActorAnimationSequences.idle_0_3;
        bomber.animation_idle = ActorAnimationSequences.idle_0_3;
        bomber.animation_swim = ActorAnimationSequences.idle_0_3;
        bomber.animation_speed_based_on_walk_speed = false;
        bomber.animation_walk_speed = 0.25f;
        bomber.animation_idle_speed = 0.25f;
        bomber.base_stats["damage"] = 1000f;
        bomber.base_stats["knockback"] = 2f;
        bomber.base_stats["accuracy"] = 0.1f;
        bomber.base_stats["targets"] = 10f;
        bomber.base_stats["area_of_effect"] = 0.5f;
        bomber.base_stats["range"] = -10f;
        bomber.default_attack = "bomb_bay";
        bomber.base_stats["attack_speed"] = -5f;
        bomber.name_template_sets = AssetLibrary<ActorAsset>.a<string>("bomber_name");
        bomber.texture_asset.loadShadow();

        ActorAsset fighter = AssetManager.actor_library.clone("warbox_fighter", "warbox_helicopter");
        fighter.icon = "actors/fighter";
        fighter.texture_asset = new ActorTextureSubAsset("actors/fighter/", false);
        fighter.name_locale = "spawn_fighter";
        fighter.power_id = "spawn_fighter";
        fighter.base_stats["mass_2"] = 1500f;
        fighter.base_stats["stamina"] = 1000f;
        fighter.base_stats["scale"] = 0.2f;
        fighter.base_stats["size"] = 1f;
        fighter.base_stats["mass"] = 1000f;
        fighter.base_stats["health"] = 800f;
        fighter.base_stats["speed"] = 80f;
        fighter.base_stats["armor"] = 5f;
        fighter.base_stats["attack_speed"] = 10f;
        fighter.base_stats["damage"] = 65f;
        fighter.base_stats["knockback"] = 2f;
        fighter.base_stats["accuracy"] = 0.5f;
        fighter.base_stats["targets"] = 1f;
        fighter.base_stats["area_of_effect"] = 0.5f;
        fighter.base_stats["range"] = 15f;
        fighter.default_height = 12f;
        fighter.default_attack = "machine_gun";
        fighter.animation_walk = ActorAnimationSequences.idle_0_3;
        fighter.animation_idle = ActorAnimationSequences.idle_0_3;
        fighter.animation_swim = ActorAnimationSequences.idle_0_3;
        fighter.animation_speed_based_on_walk_speed = false;
        fighter.animation_walk_speed = 0.25f;
        fighter.animation_idle_speed = 0.25f;
        fighter.name_template_sets = AssetLibrary<ActorAsset>.a<string>("fighter_name");
        fighter.texture_asset.loadShadow();
    }
}